/* Generated by scripts/build-episodes.mjs from the Panopto folders in data.js.
   Do not edit: changes are overwritten. Fix an episode with "overrides" in data.js. */
window.WTOP_EPISODES = [
  {
    "show": "nightly-news",
    "date": "2026-09-23",
    "title": "",
    "panoptoId": "33937c68-6e2e-4cad-9876-b4d0000472d6",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/930a6abd-0da8-46f8-863d-b4d0000472c9/1d4455ae-4c0a-4e29-ab42-b4d0000e7ccf_et/thumbs/slide27.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-22",
    "title": "",
    "panoptoId": "203baa8f-7113-4e6b-babe-b4d000046dde",
    "thumb": "",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-21",
    "title": "",
    "panoptoId": "3230dfa4-4d83-4ce3-b850-b4d000046501",
    "thumb": "",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "morning-news",
    "date": "2026-09-18",
    "title": "",
    "panoptoId": "efbe645c-4f4f-4be9-b993-b4ca01655f60",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/e932120c-89f2-4560-b7e8-b4ca01655f56/52e46cdd-daa0-4fe5-98b9-b4ca017fef9f_et/thumbs/slide12599839.jpg",
    "duration": 1664,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-17",
    "title": "",
    "panoptoId": "718dd3c9-0fa2-48f5-bd66-b4ca01655f60",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/56aeea85-f4ca-4794-819e-b4ca01655f54/11a40a4d-aad5-4d40-b013-b4ca01700e31_et/thumbs/slide12.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-15",
    "title": "",
    "panoptoId": "a5985967-57e3-444b-be8f-b4ca01654e89",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/6928dcc1-3788-44e1-b3bc-b4ca01654e7d/ed952d0b-fb9b-455e-a0c0-b4ca016c8c35_et/thumbs/slide24.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-14",
    "title": "",
    "panoptoId": "603177a1-baac-4949-9552-b4c6013f87be",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/5a127c6e-a763-44cd-993f-b4c6013f87af/cd6dd405-01ed-43bc-8a2f-b4ca017eff6a_et/thumbs/slide12599831.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-05-05",
    "title": "Senior Week",
    "panoptoId": "f399f134-439a-4b94-a93c-b48d0159ed0d",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/43d27edc-6803-4a13-9abd-b48d0159ed00/44c9f3e1-e511-4309-ac29-b48e00573021_et/thumbs/slide12347199.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-30",
    "title": "",
    "panoptoId": "4c606ab5-9639-43cd-b7ab-b48e000f02a0",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/0c3110b5-9f0a-4b10-a46b-b48e000f0295/uploadedimages/b81e789e-bd2d-416c-a164-b48e0076e73e.png",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-29",
    "title": "",
    "panoptoId": "9696491a-b172-452f-8741-b48e000f4f6e",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/420717f7-eba1-46a2-bccf-b48e000f4f62/uploadedimages/a61a0507-f60a-45eb-b7a5-b48e007736af.png",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-28",
    "title": "",
    "panoptoId": "5c55b8f3-f89b-4481-853a-b48e000fbcfc",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/b5142c26-d304-4f9a-a84b-b48e000fbcf3/uploadedimages/82570348-ca6a-46b9-a9af-b48e00775f8e.png",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-27",
    "title": "",
    "panoptoId": "dabe2524-4ed0-4683-9ff6-b48e0011e664",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/9b2903d3-a8ac-4da6-a3f6-b48e0011e659/uploadedimages/41803a2c-a7b8-4c15-832a-b48e0077856d.png",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-23",
    "title": "",
    "panoptoId": "b1575ed2-6b8d-47b4-84a7-b48e00125db6",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-21",
    "title": "",
    "panoptoId": "24294073-98c8-450f-ad27-b48e0012d2e4",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-20",
    "title": "",
    "panoptoId": "7b4cc831-a743-40e8-9a91-b48e0017fa68",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/affa6dab-5a88-4f88-8754-b48e0017fa60/8f368af4-1a4d-45eb-b5e4-b48e0021cb5f_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-16",
    "title": "",
    "panoptoId": "8d1e9ca0-57b3-42a2-80f0-b48e0018e7e0",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-15",
    "title": "",
    "panoptoId": "d2c258b6-7658-4f2a-a98b-b48e001976a9",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/75aa9663-d189-4494-ba2c-b48e001976a0/da18b9cc-3b00-460b-a4c8-b48e00228d01_et/thumbs/slide15.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-14",
    "title": "",
    "panoptoId": "a6e9d363-587c-4183-9746-b48e0019bd75",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/7c94ad20-2619-49b2-951f-b48e0019bd69/1f85d7b7-99a9-4f57-abb8-b48e00232aa7_et/thumbs/slide6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-13",
    "title": "",
    "panoptoId": "79670c84-36ce-4135-b3a9-b48e001a2cdd",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-09",
    "title": "",
    "panoptoId": "6a8d36ae-efda-4099-a5b0-b48e001c8021",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-08",
    "title": "",
    "panoptoId": "dc556948-0ad2-4815-a84c-b48e001d1f84",
    "thumb": "",
    "duration": 1799,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-07",
    "title": "",
    "panoptoId": "80c7426b-623b-4eb8-aabb-b48e001d8f94",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/9898d751-f195-4406-b567-b48e001d8f8b/ccd9b1cf-e635-4930-84f8-b48e00271b5f_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-06",
    "title": "",
    "panoptoId": "f7962439-213b-450d-a41e-b48e001e3fee",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-02",
    "title": "",
    "panoptoId": "ead7e9e3-e1bf-4a95-8dbf-b48e0052e9d3",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-01",
    "title": "",
    "panoptoId": "8b227dc3-e98d-4c81-b526-b48e0052f8d8",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-31",
    "title": "",
    "panoptoId": "8bb7fcaf-b04e-4053-b07e-b48e00531255",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/42115d36-2722-4414-b339-b48e00531245/92d98242-a5bf-42e2-bd3c-b48e005c1546_et/thumbs/slide6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-30",
    "title": "",
    "panoptoId": "42a29785-a5b7-4535-a0e9-b48e0053204b",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/7849a832-f130-4d11-a1a9-b48e0053203f/9690ec7f-0405-4354-9e5e-b48e005c14d0_et/thumbs/slide6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-26",
    "title": "",
    "panoptoId": "918d6b39-352e-487b-b578-b48e005332ff",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-25",
    "title": "",
    "panoptoId": "a9e90e47-2512-41c9-ba3b-b48e00536479",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/31917e9e-0630-4bfd-9f3c-b48e00536470/9ead30bf-389b-4eac-bae2-b48e005b9fd6_et/thumbs/slide0.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-24",
    "title": "",
    "panoptoId": "4420f150-3011-4e2d-850f-b48e005376c4",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/964900f2-13c1-417a-aaab-b48e005376ba/670144da-7866-4608-810f-b48e005be41a_et/thumbs/slide9.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-23",
    "title": "",
    "panoptoId": "309a92c6-8863-43f5-afb8-b48e005397d9",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/8b9406f1-0aee-4f58-b00a-b48e005397cf/53ddcbdf-3d78-419a-95eb-b48e005d3d55_et/thumbs/slide9.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-12",
    "title": "",
    "panoptoId": "9a5904d7-e356-46d2-9881-b48e0053bdf0",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/5980eb4f-20e8-44b4-8c79-b48e0053bde4/baf59dd9-c896-4ae0-8a28-b48e005bdd3e_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-11",
    "title": "",
    "panoptoId": "2831a610-3264-4e98-a71e-b48e0053f2d1",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/0699dff2-4d51-4a08-811c-b48e0053f2c6/6131a737-c936-4a8c-a860-b48e005db4d6_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-10",
    "title": "",
    "panoptoId": "ac49d210-dcb7-4e7e-a4d7-b48e00541e37",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/e25e5c15-0060-4124-8cf1-b48e00541e2d/bdd76e26-6091-4bfb-918a-b48e005c2842_et/thumbs/slide15.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-09",
    "title": "",
    "panoptoId": "200417d8-84eb-422e-9c0e-b48e00545d46",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/403c761a-d3de-4568-81e8-b48e00545d38/968f10fb-57aa-4cb3-8b9e-b48e005d6be7_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-05",
    "title": "",
    "panoptoId": "4480a160-96ab-4196-b7cc-b48e00548723",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-04",
    "title": "",
    "panoptoId": "a2288021-0081-481e-9825-b48e0054b3e8",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-03",
    "title": "",
    "panoptoId": "d3e74935-4286-405b-a28c-b48e0054d9f6",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/bff8aa28-6b29-4aa6-b815-b48e0054d9de/9fa2d6ba-1b55-4dad-817d-b48e005e1dc7_et/thumbs/slide12.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-02",
    "title": "",
    "panoptoId": "a457fc3a-b204-4e39-9776-b48e00550990",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/2af8fc57-0e76-4145-b0d1-b48e00550987/fec45c7f-e610-486b-9e06-b48e005e59b9_et/thumbs/slide9.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-26",
    "title": "",
    "panoptoId": "33e4e2a0-3984-4ef5-b5e6-b48e0055304c",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/8f96014b-2b53-40ae-b5af-b48e00553040/20300986-f1db-46cd-9d4e-b48e005e9bee_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-24",
    "title": "",
    "panoptoId": "153864aa-05d7-4aa5-a3f0-b48e0055563d",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/89cb60e9-5da4-4e9d-86e3-b48e00555630/fef3afea-b0a4-4f32-80c8-b48e005f1293_et/thumbs/slide6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-23",
    "title": "",
    "panoptoId": "442dcf29-bc1d-4c87-b1bb-b48e00557c90",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/acb87a03-475a-4454-afae-b48e00557c84/435bf3ef-b257-4476-a687-b48e005ecc87_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-19",
    "title": "",
    "panoptoId": "10b9fa2c-972c-45c9-b312-b48e0055a23c",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/5c9fdaf7-6961-41b7-a923-b48e0055a231/7ae6f8e1-6ef7-42dd-b220-b48e005d6992_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-18",
    "title": "",
    "panoptoId": "4adb3efc-4405-4297-b7b9-b48e0055c5f6",
    "thumb": "",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-17",
    "title": "",
    "panoptoId": "90be6330-706c-48a6-a666-b48e0055eb5d",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/6d8e7b4c-1541-4e2f-ac49-b48e0055eb54/e5121c3f-4e12-46d4-a743-b48e005de16b_et/thumbs/slide3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-16",
    "title": "",
    "panoptoId": "84ece645-697a-46ca-bc0e-b48e00560eb6",
    "thumb": "https://d2y36twrtb17ty.cloudfront.net/sessions/263f7263-e42b-40e0-9f4d-b48e00560eaa/25d59bc5-29a9-47b3-8e2c-b48e005dc58d_et/thumbs/slide6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  }
];
