/* Generated by scripts/build-episodes.mjs from the Panopto folders in data.js.
   Do not edit: changes are overwritten. Fix an episode with "overrides" in data.js. */
window.WTOP_EPISODES = [
  {
    "show": "nightly-news",
    "date": "2026-09-24",
    "title": "",
    "panoptoId": "c0635feb-4925-4908-a8fc-b4d00028b39d",
    "thumb": "thumbs/c0635feb-4925-4908-a8fc-b4d00028b39d.jpg",
    "duration": 1199,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-23",
    "title": "",
    "panoptoId": "33937c68-6e2e-4cad-9876-b4d0000472d6",
    "thumb": "thumbs/33937c68-6e2e-4cad-9876-b4d0000472d6.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-22",
    "title": "",
    "panoptoId": "203baa8f-7113-4e6b-babe-b4d000046dde",
    "thumb": "thumbs/203baa8f-7113-4e6b-babe-b4d000046dde.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-21",
    "title": "",
    "panoptoId": "3230dfa4-4d83-4ce3-b850-b4d000046501",
    "thumb": "thumbs/3230dfa4-4d83-4ce3-b850-b4d000046501.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "morning-news",
    "date": "2026-09-18",
    "title": "",
    "panoptoId": "efbe645c-4f4f-4be9-b993-b4ca01655f60",
    "thumb": "thumbs/efbe645c-4f4f-4be9-b993-b4ca01655f60.jpg",
    "duration": 1664,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-17",
    "title": "",
    "panoptoId": "718dd3c9-0fa2-48f5-bd66-b4ca01655f60",
    "thumb": "thumbs/718dd3c9-0fa2-48f5-bd66-b4ca01655f60.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-15",
    "title": "",
    "panoptoId": "a5985967-57e3-444b-be8f-b4ca01654e89",
    "thumb": "thumbs/a5985967-57e3-444b-be8f-b4ca01654e89.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "nightly-news",
    "date": "2026-09-14",
    "title": "",
    "panoptoId": "603177a1-baac-4949-9552-b4c6013f87be",
    "thumb": "thumbs/603177a1-baac-4949-9552-b4c6013f87be.jpg",
    "duration": 1800,
    "season": "Fall 2026",
    "folder": "e07377de-feb9-4d66-8296-b4ac012d34b8"
  },
  {
    "show": "entertainment-breach",
    "date": "2026-07-21",
    "title": "",
    "panoptoId": "0a2fd68c-96a7-44b8-a7a5-b48e00f42c7c",
    "thumb": "thumbs/0a2fd68c-96a7-44b8-a7a5-b48e00f42c7c.jpg",
    "duration": 1800,
    "season": "Season 5",
    "folder": "86493e33-edad-416d-8a2e-b48e000748e6",
    "undated": true,
    "episode": 3
  },
  {
    "show": "entertainment-breach",
    "date": "2026-07-21",
    "title": "",
    "panoptoId": "1376535a-0983-453e-9ead-b48e00f480e8",
    "thumb": "thumbs/1376535a-0983-453e-9ead-b48e00f480e8.jpg",
    "duration": 1800,
    "season": "Season 5",
    "folder": "86493e33-edad-416d-8a2e-b48e000748e6",
    "undated": true,
    "episode": 1
  },
  {
    "show": "entertainment-breach",
    "date": "2026-07-21",
    "title": "",
    "panoptoId": "78e7b20b-5902-4ac2-8a2c-b48e00f46bab",
    "thumb": "thumbs/78e7b20b-5902-4ac2-8a2c-b48e00f46bab.jpg",
    "duration": 1800,
    "season": "Season 5",
    "folder": "86493e33-edad-416d-8a2e-b48e000748e6",
    "undated": true,
    "episode": 2
  },
  {
    "show": "laker-showdown",
    "date": "2026-07-21",
    "title": "",
    "panoptoId": "be2a7d89-cc8d-42b0-9f92-b48e00fbead2",
    "thumb": "thumbs/be2a7d89-cc8d-42b0-9f92-b48e00fbead2.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "48ca2c81-3f79-4488-b14a-b48e00160917",
    "undated": true,
    "episode": 1
  },
  {
    "show": "be-kind-and-rewind",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "20fc423e-efa1-4603-8819-b48e00665ef8",
    "thumb": "thumbs/20fc423e-efa1-4603-8819-b48e00665ef8.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "46a1e32c-8723-45dc-8e04-b48e001b838d",
    "undated": true,
    "episode": 2
  },
  {
    "show": "entertainment-breach",
    "date": "2026-07-20",
    "title": "Senior Special 2026",
    "panoptoId": "31868cff-2fc9-4a12-8139-b48e00010484",
    "thumb": "thumbs/31868cff-2fc9-4a12-8139-b48e00010484.jpg",
    "duration": 3600,
    "season": "Season 5",
    "folder": "86493e33-edad-416d-8a2e-b48e000748e6",
    "undated": true
  },
  {
    "show": "laker-showdown",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "49cb7640-6584-48e1-b68e-b48e001a069d",
    "thumb": "thumbs/49cb7640-6584-48e1-b68e-b48e001a069d.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "48ca2c81-3f79-4488-b14a-b48e00160917",
    "undated": true,
    "episode": 2
  },
  {
    "show": "be-kind-and-rewind",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "52366525-166f-45e9-bac7-b48e0017fa72",
    "thumb": "thumbs/52366525-166f-45e9-bac7-b48e0017fa72.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "46a1e32c-8723-45dc-8e04-b48e001b838d",
    "undated": true,
    "episode": 4
  },
  {
    "show": "be-kind-and-rewind",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "618e9bcd-7b2b-4969-96c1-b48e001e1b06",
    "thumb": "thumbs/618e9bcd-7b2b-4969-96c1-b48e001e1b06.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "46a1e32c-8723-45dc-8e04-b48e001b838d",
    "undated": true,
    "episode": 3
  },
  {
    "show": "entertainment-breach",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "8c6d000a-ca9d-49b6-b4ca-b48e000f97ab",
    "thumb": "thumbs/8c6d000a-ca9d-49b6-b4ca-b48e000f97ab.jpg",
    "duration": 1800,
    "season": "Season 5",
    "folder": "86493e33-edad-416d-8a2e-b48e000748e6",
    "undated": true,
    "episode": 4
  },
  {
    "show": "be-kind-and-rewind",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "a437895b-1d06-4775-81a0-b48e0066ccb9",
    "thumb": "thumbs/a437895b-1d06-4775-81a0-b48e0066ccb9.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "46a1e32c-8723-45dc-8e04-b48e001b838d",
    "undated": true,
    "episode": 1
  },
  {
    "show": "laker-showdown",
    "date": "2026-07-20",
    "title": "",
    "panoptoId": "b033b9fc-8ac2-4599-a50e-b48e0011e664",
    "thumb": "thumbs/b033b9fc-8ac2-4599-a50e-b48e0011e664.jpg",
    "duration": 1800,
    "season": "Season 4",
    "folder": "48ca2c81-3f79-4488-b14a-b48e00160917",
    "undated": true,
    "episode": 3
  },
  {
    "show": "nightly-news",
    "date": "2026-05-05",
    "title": "Senior Week",
    "panoptoId": "f399f134-439a-4b94-a93c-b48d0159ed0d",
    "thumb": "thumbs/f399f134-439a-4b94-a93c-b48d0159ed0d.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-30",
    "title": "",
    "panoptoId": "4c606ab5-9639-43cd-b7ab-b48e000f02a0",
    "thumb": "thumbs/4c606ab5-9639-43cd-b7ab-b48e000f02a0.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-29",
    "title": "",
    "panoptoId": "9696491a-b172-452f-8741-b48e000f4f6e",
    "thumb": "thumbs/9696491a-b172-452f-8741-b48e000f4f6e.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-28",
    "title": "",
    "panoptoId": "5c55b8f3-f89b-4481-853a-b48e000fbcfc",
    "thumb": "thumbs/5c55b8f3-f89b-4481-853a-b48e000fbcfc.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-27",
    "title": "",
    "panoptoId": "dabe2524-4ed0-4683-9ff6-b48e0011e664",
    "thumb": "thumbs/dabe2524-4ed0-4683-9ff6-b48e0011e664.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-23",
    "title": "",
    "panoptoId": "b1575ed2-6b8d-47b4-84a7-b48e00125db6",
    "thumb": "thumbs/b1575ed2-6b8d-47b4-84a7-b48e00125db6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-21",
    "title": "",
    "panoptoId": "24294073-98c8-450f-ad27-b48e0012d2e4",
    "thumb": "thumbs/24294073-98c8-450f-ad27-b48e0012d2e4.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-20",
    "title": "",
    "panoptoId": "7b4cc831-a743-40e8-9a91-b48e0017fa68",
    "thumb": "thumbs/7b4cc831-a743-40e8-9a91-b48e0017fa68.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-16",
    "title": "",
    "panoptoId": "8d1e9ca0-57b3-42a2-80f0-b48e0018e7e0",
    "thumb": "thumbs/8d1e9ca0-57b3-42a2-80f0-b48e0018e7e0.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-15",
    "title": "",
    "panoptoId": "d2c258b6-7658-4f2a-a98b-b48e001976a9",
    "thumb": "thumbs/d2c258b6-7658-4f2a-a98b-b48e001976a9.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-14",
    "title": "",
    "panoptoId": "a6e9d363-587c-4183-9746-b48e0019bd75",
    "thumb": "thumbs/a6e9d363-587c-4183-9746-b48e0019bd75.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-13",
    "title": "",
    "panoptoId": "79670c84-36ce-4135-b3a9-b48e001a2cdd",
    "thumb": "thumbs/79670c84-36ce-4135-b3a9-b48e001a2cdd.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-09",
    "title": "",
    "panoptoId": "6a8d36ae-efda-4099-a5b0-b48e001c8021",
    "thumb": "thumbs/6a8d36ae-efda-4099-a5b0-b48e001c8021.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-08",
    "title": "",
    "panoptoId": "dc556948-0ad2-4815-a84c-b48e001d1f84",
    "thumb": "thumbs/dc556948-0ad2-4815-a84c-b48e001d1f84.jpg",
    "duration": 1799,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-07",
    "title": "",
    "panoptoId": "80c7426b-623b-4eb8-aabb-b48e001d8f94",
    "thumb": "thumbs/80c7426b-623b-4eb8-aabb-b48e001d8f94.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-06",
    "title": "",
    "panoptoId": "f7962439-213b-450d-a41e-b48e001e3fee",
    "thumb": "thumbs/f7962439-213b-450d-a41e-b48e001e3fee.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-02",
    "title": "",
    "panoptoId": "ead7e9e3-e1bf-4a95-8dbf-b48e0052e9d3",
    "thumb": "thumbs/ead7e9e3-e1bf-4a95-8dbf-b48e0052e9d3.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-04-01",
    "title": "",
    "panoptoId": "8b227dc3-e98d-4c81-b526-b48e0052f8d8",
    "thumb": "thumbs/8b227dc3-e98d-4c81-b526-b48e0052f8d8.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-31",
    "title": "",
    "panoptoId": "8bb7fcaf-b04e-4053-b07e-b48e00531255",
    "thumb": "thumbs/8bb7fcaf-b04e-4053-b07e-b48e00531255.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-30",
    "title": "",
    "panoptoId": "42a29785-a5b7-4535-a0e9-b48e0053204b",
    "thumb": "thumbs/42a29785-a5b7-4535-a0e9-b48e0053204b.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-26",
    "title": "",
    "panoptoId": "918d6b39-352e-487b-b578-b48e005332ff",
    "thumb": "thumbs/918d6b39-352e-487b-b578-b48e005332ff.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-25",
    "title": "",
    "panoptoId": "a9e90e47-2512-41c9-ba3b-b48e00536479",
    "thumb": "thumbs/a9e90e47-2512-41c9-ba3b-b48e00536479.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-24",
    "title": "",
    "panoptoId": "4420f150-3011-4e2d-850f-b48e005376c4",
    "thumb": "thumbs/4420f150-3011-4e2d-850f-b48e005376c4.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-23",
    "title": "",
    "panoptoId": "309a92c6-8863-43f5-afb8-b48e005397d9",
    "thumb": "thumbs/309a92c6-8863-43f5-afb8-b48e005397d9.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-12",
    "title": "",
    "panoptoId": "9a5904d7-e356-46d2-9881-b48e0053bdf0",
    "thumb": "thumbs/9a5904d7-e356-46d2-9881-b48e0053bdf0.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-11",
    "title": "",
    "panoptoId": "2831a610-3264-4e98-a71e-b48e0053f2d1",
    "thumb": "thumbs/2831a610-3264-4e98-a71e-b48e0053f2d1.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-10",
    "title": "",
    "panoptoId": "ac49d210-dcb7-4e7e-a4d7-b48e00541e37",
    "thumb": "thumbs/ac49d210-dcb7-4e7e-a4d7-b48e00541e37.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-09",
    "title": "",
    "panoptoId": "200417d8-84eb-422e-9c0e-b48e00545d46",
    "thumb": "thumbs/200417d8-84eb-422e-9c0e-b48e00545d46.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-05",
    "title": "",
    "panoptoId": "4480a160-96ab-4196-b7cc-b48e00548723",
    "thumb": "thumbs/4480a160-96ab-4196-b7cc-b48e00548723.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-04",
    "title": "",
    "panoptoId": "a2288021-0081-481e-9825-b48e0054b3e8",
    "thumb": "thumbs/a2288021-0081-481e-9825-b48e0054b3e8.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-03",
    "title": "",
    "panoptoId": "d3e74935-4286-405b-a28c-b48e0054d9f6",
    "thumb": "thumbs/d3e74935-4286-405b-a28c-b48e0054d9f6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-03-02",
    "title": "",
    "panoptoId": "a457fc3a-b204-4e39-9776-b48e00550990",
    "thumb": "thumbs/a457fc3a-b204-4e39-9776-b48e00550990.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-26",
    "title": "",
    "panoptoId": "33e4e2a0-3984-4ef5-b5e6-b48e0055304c",
    "thumb": "thumbs/33e4e2a0-3984-4ef5-b5e6-b48e0055304c.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-24",
    "title": "",
    "panoptoId": "153864aa-05d7-4aa5-a3f0-b48e0055563d",
    "thumb": "thumbs/153864aa-05d7-4aa5-a3f0-b48e0055563d.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-23",
    "title": "",
    "panoptoId": "442dcf29-bc1d-4c87-b1bb-b48e00557c90",
    "thumb": "thumbs/442dcf29-bc1d-4c87-b1bb-b48e00557c90.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-19",
    "title": "",
    "panoptoId": "10b9fa2c-972c-45c9-b312-b48e0055a23c",
    "thumb": "thumbs/10b9fa2c-972c-45c9-b312-b48e0055a23c.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-18",
    "title": "",
    "panoptoId": "4adb3efc-4405-4297-b7b9-b48e0055c5f6",
    "thumb": "thumbs/4adb3efc-4405-4297-b7b9-b48e0055c5f6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-17",
    "title": "",
    "panoptoId": "90be6330-706c-48a6-a666-b48e0055eb5d",
    "thumb": "thumbs/90be6330-706c-48a6-a666-b48e0055eb5d.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  },
  {
    "show": "nightly-news",
    "date": "2026-02-16",
    "title": "",
    "panoptoId": "84ece645-697a-46ca-bc0e-b48e00560eb6",
    "thumb": "thumbs/84ece645-697a-46ca-bc0e-b48e00560eb6.jpg",
    "duration": 1800,
    "season": "Spring 2026",
    "folder": "2615918c-73fc-4e9d-b9a1-b48e0004ad09"
  }
];
