/* Generated by scripts/build-schedule.mjs from .
   Do not edit: upload a new Cablecast CSV to schedule/ instead. */
window.WTOP_SCHEDULE_CSV = "Station ID,Program Start Date,Program Start Time,Program End Time,Duration ,Program Title,Program Description (optional),Category ,Sub Category,Time Zone?\n";
